name: Update
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "15 03 * * *"
jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: g++ curl protobuf-compiler pkg-config libprotobuf-dev
          version: 1.0
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Update rule-set branch
        run: |
          pip install proto-plus
          cd gen
          source ./rul.sh

          cd rule-set
          git init
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git branch -M rule-set
          git add --all
          git commit -m "Update rule-set on $(date '+%Y-%m-%d %H:%M')"
          git push -f origin rule-set

          cd ../routeprofiles
          git init
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git branch -M routeprofiles
          git add --all
          git commit -m "Update routeprofiles on $(date '+%Y-%m-%d %H:%M')"
          git push -f origin routeprofiles
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: routes/*.json
          tag: ${{ steps.date.outputs.date }}
          overwrite: true
          file_glob: true
